# Generated by Django 2.2 on 2022-01-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20220125_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='available',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
