# Generated by Django 2.2 on 2022-01-30 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='prodt',
            new_name='prod',
        ),
    ]
